#!/usr/bin/env bash

set -e
[ -z $D ] || set -x

export RUN_DIR=/home/vagrant/garden
export BIN_DIR=$RUN_DIR/bin
export LIBEXEC_DIR=$RUN_DIR/libexec
export DEPOT_DIR=$RUN_DIR/depot
export SNAP_DIR=$RUN_DIR/snapshots
export GRAPH_DIR=$RUN_DIR/graph
export ROOTFS_DIR=$RUN_DIR/rootfs/alice
export LOGS=$RUN_DIR/logs
export PIDFILE=$RUN_DIR/pid

case $1 in
  start)
    if [ -f "$PIDFILE" ]; then
      pid=$(head -1 "$PIDFILE")

      if [ -e /proc/$pid ]; then
        echo "Garden is already running (pid: $pid); aborting."
        exit 1
			else
				echo "Removing stale pidfile..."
				rm "$PIDFILE"
      fi
    fi

		echo -n "Starting server.."
		/usr/bin/nohup /vagrant/vagrant/start > $LOGS 2>&1 &
		until grep -q "garden-linux.started" $LOGS; do echo -n "."; sleep 1; done
		echo
    ;;

  stop)
		if ! [ -f $PIDFILE ]; then
			echo "PIDFILE $PIDFILE not found."
			exit
		fi

    pid=$(cat $PIDFILE)

		echo -n "Stopping server.."
		kill $pid > /dev/null 2>&1 || true
		while [ -e /proc/$pid ]; do sleep 1; echo -n "."; done
		echo
		rm "$PIDFILE"
    ;;
	
	hardstop)
		pid=$(cat $PIDFILE)
		echo "Stopping server with kill -9..."
		kill -9 $pid
		rm "$PIDFILE"
		;;
	restart)
		$0 stop
		$0 start
		;;
  *)
    echo "Usage: $0 {start|stop|restart|hardstop}"
    ;;
esac

