#!/usr/bin/env bash

set -e
[ -z $D ] || set -x

echo $$ > $PIDFILE
exec $BIN_DIR/garden-linux \
	-listenNetwork=tcp \
	-listenAddr=0.0.0.0:7777 \
	-depot=$DEPOT_DIR \
	-snapshots=$SNAP_DIR \
	-overlays=$OVERLAY_DIR \
	-graph=$GRAPH_DIR \
	-bin=$LIBEXEC_DIR \
	-rootfs=$ROOTFS_DIR
