---
name: garden-acceptance

director_uuid: <%= `bosh status --uuid` %>

releases:
  - name: garden-linux
    version: latest
  - name: garden-acceptance
    version: latest

jobs:
  - name: garden
    instances: 1
    templates:
      - name: sleep
        release: garden-acceptance
      - name: garden
        release: garden-linux
    resource_pool: garden
    networks:
      - name: garden

networks:
  - name: garden
    subnets:
      - range: 10.244.16.4/30
        reserved: [10.244.16.5]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.8/30
        reserved: [10.244.16.9]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.12/30
        reserved: [10.244.16.13]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.16/30
        reserved: [10.244.16.17]
        static: []
        cloud_properties:
          name: random
      - range: 10.244.16.20/30
        reserved: [10.244.16.21]
        static: []
        cloud_properties:
          name: random

resource_pools:
  - name: garden
    network: garden
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: garden
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000

properties:
  garden:
    listen_network: tcp
    listen_address: 0.0.0.0:7777
    network_mtu: 1499
    enable_graph_cleanup: false
    persistent_image_list: ["/var/vcap/packages/busybox"]
    port_pool:
      size: 5
