#!/bin/bash

set -e

[ -z $DEBUG ] || set -x && export DEBUG

depot_path=$(./scripts/get containers/$1/info | jq .ContainerPath)
cd ~/workspace/garden-linux-release
vagrant ssh -c "cd $depot_path && sudo ./bin/wsh"
