#!/bin/bash

set -e

[ -z $DEBUG ] || set -x && export DEBUG

cd $GARDEN_LINUX_RELEASE_DIR
gh nuke
gh pull
gh suir
if vagrant status | grep -Eq "default.*not created"; then
  vagrant up --provider=virtualbox
else
  vagrant provision
fi
